snorna/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^contact/$', views.contact, name = 'contact'),
    url(r'^faq/$', views.faq, name = 'faq'),
    url(r'^methods/$', views.methods, name = 'methods'),
    url(r'^download/$', views.download, name = 'download'),

    # statistics
    url(r'^statistics/$', views.statistics, name = 'statistics'),

    # basic analysis
    url(r'^basic/$', views.basic, name='basic'),
    # snorna expression
    url(r'^basic/snorna_expr_table/$', views.snorna_expr_table, name='snorna_expr_table'),
    url(r'^api/snorna_expr/$', views.api_snorna_expr, name='api_snorna_expr'),

    # tumor normal comparison
    url(r'basic/tm_comparison_table/$', views.tm_comparison_table, name='tm_comparison_table'),
    url(r'api/tm_comparison/$', views.api_tm_comparison, name='api_tm_comparison'),
    url(r'^basic/tm_comparison_table/png/(?P<encode>.*)$', views.tm_comparison_table_png, name="tm_comparison_table_png"),

    # survival
    url(r'^basic/survival_table/$', views.survival_table, name="survival_table"),
    url(r'^basic/survival_table/png/(?P<encode>.*)$', views.survival_table_png, name="survival_table_png"),
    url(r'^api/survival/$', views.api_survival, name="api_survival"),

    # diff_subtype
    url(r'^api/diff_subtype/$', views.api_diff_subtype, name="api_diff_subtype"),
    url(r'^basic/diff_subtype_table/$', views.diff_subtype_table, name='diff_subtype_table'),
    url(r'^basic/diff_subtype_table/png/(?P<encode>.*)$', views.diff_subtype_table_png, name="diff_subtype_table_png"),

    # corr_geneexpr
    url(r'^api/corr_geneexpr/$', views.api_corr_geneexpr, name="api_corr_geneexpr"),
    url(r'^basic/corr_geneexpr_table/$', views.corr_geneexpr_table, name='corr_geneexpr_table'),
    url(r'^basic/corr_geneexpr_table/png/(?P<encode>.*)$', views.corr_geneexpr_table_png, name='corr_geneexpr_table_png'),

    # corr_splicing
    url(r'^api/corr_splicing/$', views.api_corr_splicing, name="api_corr_splicing"),
    url(r'^basic/corr_splicing_table/$', views.corr_splicing_table, name='corr_splicing_table'),
    url(r'^basic/corr_splicing_table/png/(?P<encode>.*)$', views.corr_splicing_table_png, name='corr_splicing_table_png'),


    # corr_rppa
    url(r'^basic/corr_rppa_table/$', views.corr_rppa_table, name="corr_rppa_table"),
    url(r'^basic/corr_rppa_table/png/(?P<encode>.*)$', views.corr_rppa_table_png, name="corr_rppa_table_png"),
    url(r'^api/corr_rppa/$', views.api_corr_rppa, name="api_corr_rppa"),

    # corr_cnv
    url(r'^basic/corr_cnv_table/$', views.corr_cnv_table, name="corr_cnv_table"),
    url(r'^basic/corr_cnv_table/png/(?P<encode>.*)$', views.corr_cnv_table_png, name="corr_cnv_table_png"),
    url(r'^api/corr_cnv/$', views.api_corr_cnv, name="api_corr_cnv"),

    # methylation
    url(r'^basic/methylation_table/$', views.methylation_table, name="methylation_table"),
    url(r'^basic/methylation_table/png/(?P<encode>.*)$', views.methylation_table_png, name="methylation_table_png"),
    url(r'^api/methylation/$', views.api_methylation, name="api_methylation"),

    # total analysis
    url(r'^analysis/$', views.analysis, name = 'analysis'),
    # api
    url(r'^api/summary$', views.api_summary, name='api_summary'),
    url(r'^api/subtype/(?P<dataset_id>TCGA-\w*)$', views.api_subtype, name = 'api_subtype'),
    url(r'^api/snorna_list/(?P<search>.*)$', views.api_snorna_list, name='api_snorna_list'),
    url(r'^api/snorna/(?P<search>.*)$', views.api_snorna, name='api_snorna'),

    # search gene symbol
    url(r'api/gene_symbol_list/(?P<search>.*)$', views.api_gene_symbol_list, name='api_gene_symbol_list'),
    url(r'api/gene_symbol/(?P<search>.*)$', views.api_gene_symbol, name='api_gene_symbol'),

    # cnv_corr_bygene
    url(r'api/corr_cnv_bygene/$', views.api_corr_cnv_bygene, name = "api_corr_cnv_bygene"),


    # snorna_expr_bygene
    url(r'api/snorna_expr_bygene/$', views.api_snorna_expr_bygene, name="api_snorna_expr_bygene"),
    url(r'basic/snorna_expr_bygene_table/$', views.snorna_expr_bygene_table, name = "snorna_expr_bygene_table"),

    # diff_subtype_bygene
    url(r'api/diff_subtype_bygene/$', views.api_diff_subtype_bygene, name = "api_diff_subtype_bygene"),
    url(r'basic/diff_subtype_bygene_table/$', views.diff_subtype_bygene_table, name = "diff_subtype_bygene_table"),
    url(r'basic/diff_subtype_bygene_table/png/(?P<encode>.*)$', views.diff_subtype_bygene_table_png, name = "diff_subtype_bygene_table_png"),

    # survival_bygene
    url(r'api/survival_bygene/$', views.api_survival_bygene, name = "api_survival_bygene"),
    url(r'basic/survival_bygene_table/$', views.survival_bygene_table, name = "survival_bygene_table"),
    url(r'basic/survival_bygene_table/png/(?P<encode>.*)$', views.survival_bygene_table_png, name = "survival_bygene_table_png"),

    # mrna expression
    url(r'api/corr_geneexpr_bygene/$', views.api_corr_geneexpr_bygene, name = "api_corr_geneexpr_bygene"),
    url(r'basic/corr_geneexpr_bygene_table/$', views.corr_geneexpr_bygene_table, name="corr_geneexpr_bygene_table"),
    url(r'basic/corr_geneexpr_bygene_table/png/(?P<encode>.*)$', views.corr_geneexpr_bygene_table_png, name="corr_geneexpr_bygene_table_png"),

    # splicing gene based
    url(r'api/corr_splicing_bygene/$', views.api_corr_splicing_bygene, name = "api_corr_splicing_bygene"),
    url(r'basic/corr_splicing_bygene_table/$', views.corr_splicing_bygene_table, name="corr_splicing_bygene_table"),
    url(r'basic/corr_splicing_bygene_table/png/(?P<encode>.*)$', views.corr_splicing_bygene_table_png, name="corr_splicing_bygene_table_png"),

    # protein
    url(r'api/corr_rppa_bygene/$', views.api_corr_rppa_bygene, name="api_corr_rppa_bygene"),
    url(r'basic/corr_rppa_bygene_table/$', views.corr_rppa_bygene_table, name="corr_rppa_bygene_table"),
    url(r'basic/corr_rppa_bygene_table/png/(?P<encode>.*)$', views.corr_rppa_bygene_table_png, name="corr_rppa_bygene_table_png"),

    # cnv
    url(r'api/corr_cnv_bygene/$', views.api_corr_cnv_bygene, name="api_corr_cnv_bygene"),
    url(r'basic/corr_cnv_bygene_table/$', views.corr_cnv_bygene_table, name="corr_cnv_bygene_table"),
    url(r'basic/corr_cnv_bygene_table/png/(?P<encode>.*)$', views.corr_cnv_bygene_table_png, name="corr_cnv_bygene_table_png"),    # cnv
    url(r'api/methylation_bygene/$', views.api_methylation_bygene, name="api_methylation_bygene"),
    url(r'basic/methylation_bygene_table/$', views.methylation_bygene_table, name="methylation_bygene_table"),
    url(r'basic/methylation_bygene_table/png/(?P<encode>.*)$', views.methylation_bygene_table_png, name="methylation_bygene_table_png"),


    ]

snorna_data_portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include("snorna.urls", namespace = "snorna")),
    url(r'^admin/', admin.site.urls),
]

snorna/views.py
from django.shortcuts import render_to_response, render
from django.template import RequestContext, loader
from django.views.decorators.csrf import csrf_protect
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.core import serializers
from django.apps import apps

from .models import *
import json
import base64
import subprocess
import os.path, sys

# resource and r scripts dir
rcommand = '/usr/bin/Rscript'
rscript_dir = os.path.dirname(os.path.abspath(__file__)) + '/rscripts/'
resource_jons = os.path.dirname(os.path.abspath(__file__)) + '/resource/jsons/'
resource_pngs = os.path.dirname(os.path.abspath(__file__)) + '/resource/pngs/'


# main home page
def index(request):
    title = "SNORic"
    context = {"title": title}

    return render(request, 'snorna/index.html', context)

# contact info
def contact(request):
    title = "SNORic | Contact"
    context = {
        "title": title
    }
    return render(request, 'snorna/contact.html', context)


# faq
def faq(request):
    title = "SNORic | FAQ"
    context = {
        "title": title
    }

    return render(request, 'snorna/faq.html', context)


# methods
def methods(request):
    title = "SNORic | Methods"
    context = {
        "title": title
    }
    return render(request, 'snorna/methods.html', context)


def download(request):
    title = "SNORic | API"
    context = {
        "title": title
    }
    return render(request, 'snorna/download.html', context)


def statistics(request):
    title = "SNORic | Statistics"
    context = {
        "title": title,
    }
    return render(request, 'snorna/statistics.html', context)


# basic analysis
def basic(request):
    title = "SNORic | Basic"
    context = {
        "title": title
    }
    return render(request, 'basic/main.html', context)


def get_expression(request):
    q_name = request.GET["genes"]
    dataset_id =  request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    # subtype == "0"
    # subtype == "all"
    # subtype == "subtype"
    model_str = "snorna_expression_" + dataset_id.replace("TCGA-","")
    model = apps.get_model("snorna", model_str)
    snorna_expr = model.objects.using('snoric').filter(
        dataset_id__exact=dataset_id,
        snorna__exact=q_name).values('dataset_id',
                                     'snorna',
                                     'sample_id',
                                     'snorna_expression')
    return snorna_expr


def snorna_expr_table(request):
    title = "SNORic | snorna expression"
    context = {"title": title}
    return render(request, 'basic/dataTables/snorna_expr_table.html', context)


def api_snorna_expr(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_snorna_expr.r", arg]
    json_file = resource_jons + arg + ".snorna_expr.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)

def api_tm_comparison(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    return JsonResponse({'png_name': arg})

def tm_comparison_table(request):
    title = "SNORic | tm comparison"
    context = {"title": title}
    return render(request, 'basic/dataTables/tm_comparison_table.html', context)

def tm_comparison_table_png(request, encode):
    png = resource_pngs + encode + ".tm_comparison.png"
    if os.path.exists(png):
        with open(png) as f:
            return HttpResponse(f.read(), content_type = "image/png")
    else:
        return HttpResponse("Not enough samples!", content_type = "text/plain")

# survival
def survival_table(request):
    title = "SNORic | survival"
    context = {"title": title}
    return render(request, 'basic/dataTables/survival_table.html', context)


def survival_table_png(request, encode):
    encode = encode + ".survival.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")


def api_survival(request):
    # snorna = snorna_info.objects.using('snoric').get(snorna__exact=request.GET["genes"])
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_survival.r", arg]
    json_file = resource_jons + arg + ".survival.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)


# diff_subtype
def diff_subtype_table(request):
    title = "SNORic | diff_subtype"
    context = {"title": title}
    return render(request, 'basic/dataTables/diff_subtype_table.html', context)


def api_diff_subtype(request):
    # snorna = snorna_info.objects.using('snoric').get(snorna__exact=request.GET["genes"])
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    arg = base64.b64encode(q_name + "#" + dataset_id)
    cmd = [rcommand, rscript_dir + "basic_diff_subtype.r", arg]
    json_file = resource_jons + arg + ".diff_subtype.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)


def diff_subtype_table_png(request, encode):
    encode = encode + ".diff_subtype.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")


# corr_geneexpr
def api_corr_geneexpr(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_corr_geneexpr.r", arg]
    json_file = resource_jons + arg + ".corr_geneexpr.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)

def corr_geneexpr_table(request):
    title = "SNORic | corr_geneexpr"
    context = {"title": title}
    return render(request, 'basic/dataTables/corr_geneexpr_table.html', context)

def corr_geneexpr_table_png(request, encode):
    encode = encode + ".corr_geneexpr.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")

# corr_splicing
def api_corr_splicing(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_corr_splicing.r", arg]
    json_file = resource_jons + arg + ".corr_splicing.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)

def corr_splicing_table(request):
    title = "SNORic | corr_splicing"
    context = {"title": title}
    return render(request, 'basic/dataTables/corr_splicing_table.html', context)

def corr_splicing_table_png(request, encode):
    encode = encode + ".corr_splicing.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")


# corr_rppa
def corr_rppa_table(request):
    title = "SNORic | corr_rppa"
    context = {"title": title}
    return render(request, 'basic/dataTables/corr_rppa_table.html', context)

def api_corr_rppa(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_corr_rppa.r", arg]
    json_file = resource_jons + arg + ".corr_rppa.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)

def corr_rppa_table_png(request, encode):
    encode = encode + ".corr_rppa.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")

# corr_cnv
def corr_cnv_table(request):
    title = "SNORic | corr_cnv"
    context = {"title": title}
    return render(request, 'basic/dataTables/corr_cnv_table.html', context)

def api_corr_cnv(request):
    q_name = request.GET["genes"]
    dataset_id = request.GET["dataset_ids"]
    subtype_id = request.GET["subtype_id"]
    arg = base64.b64encode(q_name + "#" + dataset_id + "#" + subtype_id)
    cmd = [rcommand, rscript_dir + "basic_corr_cnv.r", arg]
    json_file = resource_jons + arg + ".corr_cnv.json"
    if not os.path.exists(json_file):
        subprocess.check_output(cmd, universal_newlines=True)
    data = json.load(open(json_file, 'r'))
    return JsonResponse(data, safe=False)

def corr_cnv_table_png(request, encode):
    encode = encode + ".corr_cnv.png"
    png = resource_pngs + encode
    with open(png) as f:
        return HttpResponse(f.read(), content_type="image/png")


# methylation
def methylation_table(request):
    title = "SNORic | methylation"
    context = {"title": title}
    return render(request, 'basic/dataTables/methylation_table.html', context)

def methylation_table_png(request, encode):
    encode = encode + ".methylation.png"
    png = resource_pngs + encode

snorna/templates/snorna/header.html
{% load staticfiles %}
<header class="navbar navbar-inverse navbar-static-top " id="bs-navbar" role="banner">
    <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-navbar" aria-controls="bs-navbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="{% url 'snorna:index' %}">
                <span ><i class="fa fa-home" aria-hidden="true"></i></span>
                <span>SNORic (snoRNA in cancers)</span>
            </a>
        </div>
        <nav class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'snorna:index' %}"><i class="fa fa-home"></i>&nbsp;Home</a></li>
{#                <li ><a href="{% url 'snorna:faq' %}"><i class="glyphicon glyphicon-stats"></i>&nbsp;FAQ</a></li>#}
                <li ><a href="{% url 'snorna:methods' %}"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;Document</a></li>
{#                <li ><a href="{% url 'snorna:download' %}"><i class="fa fa-download" aria-hidden="true"></i>&nbsp;Download</a></li>#}
                <li ><a href="{% url 'snorna:contact' %}"><i class="glyphicon glyphicon-envelope"></i>&nbsp;Contact</a></li>
            </ul>
        </nav>
	</div>
</header>

snorna/templates/snorna/index.html
{% extends "snorna/base.html" %} {% load staticfiles %} {% block title %}{{ title }}{% endblock %} {% block content %}
<!-- <div class="jumbotron">
    <div class="container">
        <h2>Welcome to SNORic</h2>
        <p class="text-justify">The <span class="text-danger">SNORic</span> refers to "snoRNA in cancer". Small nucleolar RNAs (snoRNAs) are a class of regulatory non-coding RNAs, which play a conserved role in ribosome biogenesis. However, in recent years, increasing evidence has demonstrated snoRNAs play important roles in tumorigenesis. Here, we systematically analyzed snoRNA expression profiles in > 10,000 samples across 31 cancer types from The Cancer Genome Atlas, and analyzed their correlation with other TCGA genomic,proteomic, epigenomic and clinical data (e.g. patient tumor stage, subtype, and survival).
        </p>
    </div>
</div> -->

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">SNORic</h3>
            </div>
            <div class="panel-body text-justify" style="padding:17px 20px; font-size:17px; height:270px">
                <P>The <span class="text-danger">SNORic</span> refers to "snoRNA in cancers". Small nucleolar RNAs (snoRNAs) are a class of regulatory non-coding RNAs, which play a conserved role in ribosome biogenesis. However, in recent years, increasing
                    evidence has demonstrated that snoRNAs play important roles in tumorigenesis. Here, we systematically analyzed snoRNA expression profiles in > 10,000 samples across 31 cancer types from The Cancer Genome Atlas, and analyzed their correlation
                    with other TCGA genomic, proteomic, epigenomic and clinical data (e.g. patient tumor stage, subtype, and survival).</p>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Users Can:</h3>
            </div>
            <div class="panel-body" style="padding:15px 10px; font-size:16px; height:270px">
                <dl class="dl-horizontal">
                    <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                    <dd>Search snoRNA expression in different cancer types;
                        <dd>
                            <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                            <dd>Analyze the differential expressed snoRNAs between tumor and normal samples; </dd>
                            <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                            <dd>Analyze the correlation between snoRNA and clinical stage/subtype/survival;</dd>
                            <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                            <dd>Analyze the correlation between snoRNA and snoRNA CNV/methylation;</dd>
                            <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                            <dd>Analyze the correlation between snoRNA and gene mRNA/splicing/protein;</dd>
                            <dt><span class="glyphicon glyphicon-tag" aria-hidden="true" style="color:red"></span></dt>
                            <dd>Download all expression data to independently validate a pattern of interest.</dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
    <div class="panel panel-info">
        <div class="panel-body" style = "margin: 10px 0px">
            <div class="col-md-1"><strong>Citation:</strong></div>
            <div class="col-md-11">
            <a href="http://www.cell.com/cell-reports/fulltext/S2211-1247(17)31533-4" target="_blank"><strong>A Pan-cancer Analysis of the Expression and Clinical Relevance of Small Nucleolar RNAs in Human Cancer.</strong></a><br />
            <span>Jing Gong<sup>&dagger;</sup>, Yajuan Li<sup>&dagger;</sup>, Chun-Jie Liu<sup>&dagger;</sup>, Yu Xiang <sup>&dagger;</sup>, Chunlai Li, Youqiong Ye, Zhao Zhang, David H. Hawke, Peter K. Park, Lixia Diao, John A. Putkey, Liuqing Yang, An-Yuan Guo<sup>&lowast;</sup>, Chunru Lin<sup>&lowast;</sup>, Leng Han<sup>&lowast;</sup>.</span>
            <span>Cell Reports. (2017).</span>
            </div>
        </div>
    </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="penal panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Summary of samples</h3>
            </div>
            <div class="panel-body">
                <a href="{% url 'snorna:statistics' %}" class="thumbnail">
                        <img src="{% static 'image/dataset_summary.svg' %}" style="height: 240px">
                    </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="penal panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">snoRNA based analysis</h3>
            </div>
            <div class="panel-body">
                <a href="{% url 'snorna:basic' %}" class="thumbnail">
                        <img src="{% static 'image/individual_snoRNA.png' %}" style="height: 240px" />
                    </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="penal panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Gene based analysis</h3>
            </div>
            <div class="panel-body">
                <a href="{% url 'snorna:analysis' %}" class="thumbnail">
                        <img src="{% static 'image/all_snoRNAs.png' %}" style="height: 240px"/>
                    </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="penal panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Download</h3>
            </div>
            <div class="panel-body">
                <a href="{% url 'snorna:download' %}" class="thumbnail">
                        <img src="{%  static 'image/download_3.png' %}" style="height: 240px">
                    </a>
            </div>
        </div>
    </div>
</div>

<div id="carousel-snoric" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-snoric" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-snoric" data-slide-to="1"></li>
        <li data-target="#carousel-snoric" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox" style="margin-top:20px;">
        <div class="item active">
            <img src="{%  static 'image/database_sample_numbers_barplot.png' %}" alt="database_sample_numbers_barplot">
            <!-- <div class="carousel-caption" style="color: blue;">
                <h3>Snoric Samples</h3>
                <p>We obtain blablabla sample</p>
            </div> -->
        </div>
        <div class="item">
            <img src="{%  static 'image/database_number_of_detectable_snoRNAs.png' %}" alt="database_number_of_detectable_snoRNAs">
            <!-- <div class="carousel-caption">
                <h3>Detectable snoRNA in SNORic</h3>
                <p>hhl</p>
            </div> -->
        </div>
        <div class="item">
            <img src="{%  static 'image/database_number_of_cnv_cor_snoRNAs.png' %}" alt="database_number_of_detectable_snoRNAs">
            <!-- <div class="carousel-caption">
                <h3>Detectable snoRNA in SNORic</h3>
                <p>hhl</p>
            </div> -->
        </div>
        <div class="item">
            <img src="{%  static 'image/database_number_of_methy_cor_snoRNAs.png' %}" alt="database_number_of_detectable_snoRNAs">
            <!-- <div class="carousel-caption">
                <h3>Detectable snoRNA in SNORic</h3>
                <p>hhl</p>
            </div> -->
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-snoric" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-snoric" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
{% endblock %}